import Navbar from './components/Navbar'
import QueryProvider from './components/QueryProvider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <div className='container mx-auto my-8'>
          <Navbar />
          {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  )
}
